### ISSUE TITLE
PreCrawlingPlugin Interface

### ISSUE THREAD

**Issue by Euphie** [crawljax/crawljax#337]
HI:
I want to crawl before calling PreCrawlingPlugin interfaces in order to login to a website , but I found the interface does not return the context object, then how can I get a handle of the browser, and operate elements on the page?

**Comment by maria456123** [comment]
private static InputSpecification getInputSpecification() {
		InputSpecification input = new InputSpecification();
		  input.inputField(InputType.TEXT,identification);
		  return input;
	}
"input.field" is not available in version 4.1, it rather has InputField which takes two parameters input type and 2nd is identification, please guide me on how can I set the Identification of element.

**Comment by yrahulkr** [comment]
Identification is how you identify the target web element. It could be things like "xpath" or "id". Here is the [identification class](https://github.com/crawljax/crawljax/blob/master/core/src/main/java/com/crawljax/core/state/Identification.java) in crawljax. 

Here is an example usage. 


		FormInput username = loginForm.inputField(InputType.TEXT, new Identification(How.name, "user"));
		username.inputValues("admin");
