### ISSUE TITLE
Fix verbosity level for Web-UI logs

### ISSUE THREAD

**Issue by keheliya** [crawljax/crawljax#408]
`com.crawljax.web.SocketLogAppender` depends on the root log level in `web/src/main/config/logback.xml`. So if it's set to `WARN`, crawl logs in Web UI stops working and file appender also won't have crawl records. Proper fix is to set the root log level to `INFO`and set a ThresholdFilter for everything below `WARN` for console logs to reduce noise.

This is related to #382, #406, #385

**Comment by amaniSaleh** [comment]
I'm a beginner in crawljax, I'm facing the same problem in #382. Can you please show exactly what to change in the logback.xml file?
