### ISSUE TITLE
Crawljax not working with Firefox 32.0.2

### ISSUE THREAD

**Issue by malerisch** [crawljax/crawljax#443]
Hi,

Crawljax 3.5.1 does not work with Firefox 32.0.2 - I think this might be related to a bug in Selenium: https://code.google.com/p/selenium/issues/detail?id=7642

It appears that the solution is to upgrade Selenium.

Cheers,

Roberto

**Comment by tsigalko18** [comment]
Major updates occurred in the drivers. #512 uses WebDriverManager and should work fine
