### ISSUE TITLE
Crawling websites using https through a proxy

### ISSUE THREAD

**Issue by phkrug** [crawljax/crawljax#456]
We are using Crawljax through a proxy to gather some additional information. The website we are crawling uses https. The result is an certificate error in the browser. With the current state of Crawljax it would not be possible to crawl this site.

One solution is to add the command line argument "--ignore-ssl-errors=true" to the PhantomJS call and respective options for the other browsers. We are aware of the implications regarding the security and therefore wouldn't mind a switch to turn this option on and off. The version we are using at the moment has this option hardcoded to the command line arguments.

**Comment by fishouttah20** [comment]
Use a proxy that generates a certificate and add it to your local trust store. Fiddler allows you to MITM HTTPS traffic via this method.
