### ISSUE TITLE
Build fails on Mac OS

### ISSUE THREAD

**Issue by gzoller** [crawljax/crawljax#458]
Downloaded the 3.6.zip source and did a build with 'mvn clean package'
Rolled for a bit then gave me this error:

[INFO] Reactor Summary:
[INFO]
[INFO] Crawljax parent POM ................................ SUCCESS [  1.643 s]
[INFO] Crawljax core ...................................... FAILURE [  0.878 s]
[INFO] Crawljax test utilities ............................ SKIPPED
[INFO] Crawljax plugins parent POM ........................ SKIPPED
[INFO] Crawl Overview Plugin .............................. SKIPPED
[INFO] Crawljax CLI ....................................... SKIPPED
[INFO] Crawljax Examples .................................. SKIPPED
[INFO] Test Plugin ........................................ SKIPPED
[INFO] Crawljax plugins archetype ......................... SKIPPED
[INFO] Crawljax web interface ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.775 s
[INFO] Finished at: 2015-01-22T11:16:21-06:00
[INFO] Final Memory: 15M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project crawljax-core: Fatal error compiling: invalid target release: 1.7 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :crawljax-core

**Comment by amesbah** [comment]
The failure is due to the git-commit-id-plugin. If you clone the source code from GitHub, it should work fine. 

But when you download the source, the plugin needs to be disabled in the pom.xml. @alexnederlof do you have any suggestions?
