### ISSUE TITLE
i can't get crawl content from crawljax.

### ISSUE THREAD

**Issue by bass14** [crawljax/crawljax#459]
I have crawl Dynamic webpage using Crawljax. i can able to get crawl current id, status and dom. but i can't get the Website content.. Any one help me??

CrawljaxConfigurationBuilder builder =
            CrawljaxConfiguration.builderFor("http://demo.crawljax.com/");
    builder.addPlugin(new OnNewStatePlugin() {

        @Override
        public String toString() {
            return "Our example plugin";
        }

                @Override
                public void onNewState(CrawlerContext cc, StateVertex sv) {

                    LOG.info("Found a new dom! Here it is:\n{}", cc.getBrowser().getStrippedDom());
                       String name = cc.getCurrentState().getName();
String url = cc.getBrowser().getCurrentUrl();
System.out.println(cc.getCurrentState().getDom());
System.out.println("New State: " + name + "; url: " + url);
                }
    });
    CrawljaxRunner crawljax = new CrawljaxRunner(builder.build());
    crawljax.call();

How to get dynamic/java script Webpage content..

**Comment by valenciadominic** [comment]
were you able to find how to do it?

**Comment by amesbah** [comment]
The DOM instance that you receive from getCurrentState().getDom() is the dynamic DOM tree. It contains JS mutations performed on the DOM at runtime.

**Comment by valenciadominic** [comment]
What I'm trying to do is to get text or the content of an HTML tag, for example <div>text</div>.

I'm new with crawljax, right now I'm using another library named Jsoup to parse the HTML returned by getDom();

**Comment by valenciadominic** [comment]
@amesbah I have a situation here, I need to select a value from a dropdown? how can I achieve this using crawljax? I'm using crawljax to crawl a dymanic web app to get specific data. Please help..
