### ISSUE TITLE
UrlValidator does not recognize new TLDs

### ISSUE THREAD

**Issue by kravietz** [crawljax/crawljax#474]
The org.apache.commons.validator.routines.UrlValidator as used in [https://github.com/crawljax/crawljax/blob/ffb84cba861c0bb6758fe0a117b61bb8f8c3112a/cli/src/main/java/com/crawljax/cli/ParameterInterpeter.java#L16 ParameterInterpeter.java] does not recognize new TLDs and treats them as invalid URLs:

```
java -jar crawljax-cli-3.6.jar https://passphrase.today/ pass 
provide a valid URL like http://example.com
```

Obviously, the [https://passphrase.today/ passphrase.today] is a valid and working domain.

**Comment by fernandobrito** [comment]
Crawljax currently uses Apache Commons Validator 1.4.0
Latest version (1.4.1) was updated with a more recent TLD list, as seen here: https://issues.apache.org/jira/browse/VALIDATOR-348

I will update this dependency, see if tests are still passing and report here soon.

**Comment by fishouttah20** [comment]
A command line to bypass the validator would be ideal. Thousands of new TLDs have been and will continue to be added.
