### ISSUE TITLE
Purpose of the proxy-plugin

### ISSUE THREAD

**Issue by viyatb** [crawljax/crawljax#475]
Hi, the proxy-plugin repo doesn't contain a README/ or has no information what it is.
I am looking to pass all the Crawljax traffic though a proxy. How can I do this? Is this the proxy-plugin is for?

**Comment by fernandobrito** [comment]
Hi!

Did you take a look at this example file on proxy-plugin? https://github.com/crawljax/proxy-plugin/blob/master/src/main/java/com/crawljax/plugins/proxy/examples/ProxyPluginExample.java

**Comment by delta24** [comment]
Yes, but what I meant was: can I route all the Crawljax traffic through a MiTm proxy like Burp proxy or Zapproxy without writing some Java code?
