### ISSUE TITLE
Expose a REST-like API

### ISSUE THREAD

**Issue by delta24** [crawljax/crawljax#476]
I am testing a target and I need the ability to control Crawljax from my script which is in Python. Is there a functionality to do so? Or is only JAVA supported?

Thanks!

**Comment by fernandobrito** [comment]
Hmmm. Isn't Crawljax's web module an angular.js app consuming an "internal" REST service? But I can't find any good documentation on that (endpoints and so on).

**Comment by delta24** [comment]
I think its accessible internally, if you write a JAVA app. I want to control externally from a script.
IMO its easy to implement. Expose the ReST like urls, to the internal JAVA based methods.
