### ISSUE TITLE
How to use the crawl overview plugin programatically?

### ISSUE THREAD

**Issue by delta24** [crawljax/crawljax#485]
I am using the Advanced example given in the `examples` folder. I added a separate line
`builder.addPlugin(new CrawlOverview());`. On running the example, it results in error

```
16:37:31.908 [main] ERROR - Plugin Crawl overview plugin errored while running. Directory must be empty
java.lang.IllegalArgumentException: Directory must be empty
```

**Comment by TobEnd** [comment]
Your output-folder seems to exist already.

maybe do s.t. like this to make sure that a new folder is created each time
`builder.setOutputDirectory(new File(new SimpleDateFormat("MM.dd-HH_mm_ss").format(new Date())));`

**Comment by delta24** [comment]
I resolved it a long time ago but forgot to close this issue. Thanks for the input though! :)
