### ISSUE TITLE
Web UI doesn't work

### ISSUE THREAD

**Issue by alishir** [crawljax/crawljax#495]
Nothing happened after unzipping `crawljax-web-3.6-distribution.zip` and running with `java -jar crawljax-web-3.6.jar` in `crawljax-web-3.6` directory.

**Comment by fernandobrito** [comment]
Hello @alishir. Please try to open http://localhost:8080/ on your browser. You should see this web interface: http://crawljax.com/blog/2014/03/07/crawljax-gets-a-face-lift-web-ui-in-crawljax-3-dot-5/

@amesbah I am not sure, but it seems this is not documented anywhere. Should I include a message similar to "Service started on port 8080" on the console or maybe even open it on the browser for the user?

**Comment by alishir** [comment]
Hello @fernandobrito. Thanks for your comment. I read that post but nothing there about `localhost:8080`.
Thanks.

**Comment by amesbah** [comment]
It is mentioned here: https://github.com/crawljax/crawljax/tree/master/web
