### ISSUE TITLE
java.lang.AbstractMethodError  when adding " builder.addPlugin(new CrawlOverview())"

### ISSUE THREAD

**Issue by arcuri82** [crawljax/crawljax#496]
Hi,
 I am evaluating different crawlers for Java, and I gave a try to Crawljax. However, when I try to use its overview plugin I get the following exception:

java.lang.AbstractMethodError: com.crawljax.plugins.crawloverview.CrawlOverview.preStateCrawling(Lcom/crawljax/core/CrawlerContext;Lcom/google/common/collect/ImmutableList;Lcom/crawljax/core/state/StateVertex;)V

	at com.crawljax.core.plugin.Plugins.runPreStateCrawlingPlugins(Plugins.java:286)
	at com.crawljax.core.Crawler.crawlIndex(Crawler.java:457)
	at com.crawljax.core.CrawlTaskConsumer.crawlIndex(CrawlTaskConsumer.java:85)
	at com.crawljax.core.CrawlController.call(CrawlController.java:66)
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37)

I am using Java 8 on Windows 7. From Maven, I have:

        <dependency>
            <groupId>com.crawljax</groupId>
            <artifactId>crawljax-core</artifactId>
            <version>3.6</version>
        </dependency>
        <dependency>
            <groupId>com.crawljax.plugins</groupId>
            <artifactId>crawloverview</artifactId>
            <version>1.2</version>
        </dependency>

I am running Crawljax with:

 CrawljaxConfiguration.CrawljaxConfigurationBuilder builder = CrawljaxConfiguration.builderFor(getBaseUrl());
        builder.setMaximumRunTime(MAX_MINUTES, TimeUnit.MINUTES);
        builder.setMaximumDepth(50);
        builder.setMaximumStates(2000);

        builder.setBrowserConfig(new BrowserConfiguration(EmbeddedBrowser.BrowserType.CHROME, 1)); 
        builder.crawlRules().dontClick("a").withAttribute("class", "image-link");

        builder.crawlRules().waitAfterReloadUrl(1000, TimeUnit.MILLISECONDS);
        builder.crawlRules().waitAfterEvent(200, TimeUnit.MILLISECONDS);

        builder.addPlugin(new CrawlOverview());  //this does crash

        InputSpecification input = new InputSpecification();
        //be sure we can login
        input.field("username1").setValue(name);
        input.field("password1").setValue(password);
        builder.crawlRules().setInputSpec(input);

        CrawljaxRunner crawljax = new CrawljaxRunner(builder.build());
        try {
            crawljax.call();
        } finally {
            crawljax.stop();
        }

**Comment by amesbah** [comment]
<version>36</version> expects Java 7.

**Comment by amesbah** [comment]
If you need to run it with Java 8 on Windows, try building the code from the master branch using Maven:

     mvn package -DskipTests 

(We have noticed that some test cases fail on Windows due to environmental settings, hence -DskipTests, but the build should work fine)

**Comment by arcuri82** [comment]
Hi, 
  thanks for the quick response. I am using 3.6 as it seems the latest stable release from Maven Central:

http://mvnrepository.com/artifact/com.crawljax/crawljax-core

however, it looks like it is 1 year old. Is there any new release planned for the future?

Compiling from source is doable, but quite cumbersome, as I would need to install it on many different machines (eg colleagues' desktops and remote Jenkins/Bamboo). It can be installed on a corparate Nexus, but I would need to look into it. However, something to consider in the future if the other crawlers I am evaluating do not work well :) 

thanks

Andrea

**Comment by amesbah** [comment]
No new release planned for anytime soon. We are however working on a cloud-based version, which  removes the need to build/install/etc.

**Comment by arcuri82** [comment]
I see. That is unfortunate. Anyway, thanks for the clarification.

**Comment by Santhz77** [comment]
Hi, 
When I tried the above and still tried to set the jdk to 7, the same problem exists.
thanks,
Santy
