### ISSUE TITLE
mvn install fails

### ISSUE THREAD

**Issue by praveenshukla10** [crawljax/crawljax#498]
I am trying to install a jar file through maven 3.1.1 which fails with the below error. Any help is highly appreciated..

C:\Softwares\apache-maven-3.1.1-bin\apache-maven-3.1.1\bin>mvn install:install-file -Dfile=C:\work\usi\usijars\auskey-dep-1.1.jar -DgroupId=au.gov -DartifactId=auskey-dep -Dversion=1.1 -Dpackaging=jar
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 28.9 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-clean-plugin:jar:2.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-clean-plugin:2.5: Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom (4 KB at 127.4 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-install-plugin:jar:2.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-install-plugin:2.4: Plugin org.apache.maven.plugins:maven-install-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-install-plugin:jar:2.4
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/2.7/maven-deploy-plugin-2.7.pom (4 KB at 167.9 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-deploy-plugin:jar:2.7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-deploy-plugin:2.7: Plugin org.apache.maven.plugins:maven-deploy-plugin:2.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-deploy-plugin:jar:2.7
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.pom (4 KB at 142.1 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-site-plugin:jar:3.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-site-plugin:3.3: Plugin org.apache.maven.plugins:maven-site-plugin:3.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-site-plugin:jar:3.3
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom (4 KB at 153.9 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-antrun-plugin:jar:1.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-antrun-plugin:1.3: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-antrun-plugin:jar:1.3
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (4 KB at 51.3 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-assembly-plugin:jar:2.2-beta-5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-assembly-plugin:jar:2.2-beta-5
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom (4 KB at 131.9 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-dependency-plugin:jar:2.8 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-dependency-plugin:2.8: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-dependency-plugin:jar:2.8
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.3.2/maven-release-plugin-2.3.2.pom (4 KB at 40.2 KB/sec)
[WARNING] The POM for org.apache.maven.plugins:maven-release-plugin:jar:2.3.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-release-plugin:2.3.2: Plugin org.apache.maven.plugins:maven-release-plugin:2.3.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-release-plugin:jar:2.3.2
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (4 KB at 167.9 KB/sec)
[WARNING] Checksum validation failed, expected <!DOCTYPE but is b3770e124b987410ea3343f602217c4c847a41bf for http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (4 KB at 92.4 KB/sec)
[WARNING] The metadata C:\Users\pps3.m2\repository\org\apache\maven\plugins\maven-metadata-central.xml is invalid: end tag name </form> must match start tag name <div> from line 24 (position: TEXT seen ...</div>\n    </form>... @58:12)
[WARNING] The metadata C:\Users\pps3.m2\repository\org\codehaus\mojo\maven-metadata-central.xml is invalid: end tag name </form> must match start tag name <div> from line 24 (position: TEXT seen ...</div>\n    </form>... @58:12)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.313s
[INFO] Finished at: Mon Apr 11 14:56:31 EST 2016

**Comment by amesbah** [comment]
Crawljax 4.1 should resolve such issues.
