### ISSUE TITLE
Running crawljax for a given period of time

### ISSUE THREAD

**Issue by aishwaryakapse** [crawljax/crawljax#500]
Hi,
I want to run crawljax for a particular given period of time (say 1 hour) and then stop crawling. How do I implement this? Is it possible to stop crawljax programmatically after it has run for a given period of time. If it possible to give the run time to the crawler?

Thanks
-Aishwarya

**Comment by amesbah** [comment]
You can specify a maximum run time with setMaximumRunTime 

     CrawljaxConfigurationBuilder builder = CrawljaxConfiguration.builderFor("http://your.website.com");
     builder.setMaximumRunTime(long time, TimeUnit unit);

**Comment by aishwaryakapse** [comment]
Thank you very much.....
