### ISSUE TITLE
How To Run Crawljax 4.0 maven on eclipse

### ISSUE THREAD

**Issue by MedoFawzy** [crawljax/crawljax#503]
Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Crawljax parent POM
[INFO] Crawljax DOM Strippers
[INFO] Crawljax core
[INFO] Crawljax plugins parent POM
[INFO] Crawl Overview Plugin
[INFO] Crawljax CLI
[INFO] Crawljax Examples
[INFO] Test Plugin
[INFO] Crawljax plugins archetype
[INFO] Crawljax web interface
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Crawljax parent POM ................................ SKIPPED
[INFO] Crawljax DOM Strippers ............................. SKIPPED
[INFO] Crawljax core ...................................... SKIPPED
[INFO] Crawljax plugins parent POM ........................ SKIPPED
[INFO] Crawl Overview Plugin .............................. SKIPPED
[INFO] Crawljax CLI ....................................... SKIPPED
[INFO] Crawljax Examples .................................. SKIPPED
[INFO] Test Plugin ........................................ SKIPPED
[INFO] Crawljax plugins archetype ......................... SKIPPED
[INFO] Crawljax web interface ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.337 s
[INFO] Finished at: 2016-10-03T17:41:29+02:00
[INFO] Final Memory: 6M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

**Comment by MartinRogalla** [comment]
This not a Crawljax issue. Read up on how to use maven. As maven tells you:
> [ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format : or :[:]:. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

What is your goal; what are you trying to do? As explained in the readme you can try using `mvn clean package` to compile and run the tests.

If you have issues specifying maven goals or lifecycles in Eclipse have a look at the following article:
https://books.sonatype.com/m2eclipse-book/reference/running-sect-running-maven-builds.html

**Comment by MedoFawzy** [comment]
I want to crawl http link have ajax

how to do ??
