### ISSUE TITLE
 Reply ASAP -Not working with any browser other than firefox 

### ISSUE THREAD

**Issue by shivam-shipankar** [crawljax/crawljax#506]
i am currently working with crawljax latest release(jar file) on cmd prompt. its only working with firefox. i want to change the browser how can .. tried everything from setting environment to installing drivers of chrome still not able to do that help !!!!
cmd command - java -jar crawljax.cli.3.6.jar "http://www.google.com" "1"

**Comment by TobEnd** [comment]
https://github.com/crawljax/crawljax/blob/master/cli/README.md

**Comment by tsigalko18** [comment]
In #512 WebDriverManager is used to provide the latest drivers. I haven't tried the command line, but programmatically it works for me
