### ISSUE TITLE
Is this repo going to be maintained?

### ISSUE THREAD

**Issue by psiinon** [crawljax/crawljax#509]
We use Crawljax in [ZAP](https://github.com/zaproxy/zaproxy) and need to make some improvements to it.
Ideally we'd like to submit these improvements back to this repo but it looks like it hasnt been updated for some time.
We will be happy to take over maintenance of this repo, or otherwise fork it and maintain that fork until such time as this repo is maintained again. We will be primarily maintaining our fork for ZAP but will also be happy consider other PRs.

**Comment by amesbah** [comment]
Hi Simon,
Yes, we are still maintaining Crawljax and there will be a major release, hopefully soon. 

In the mean time, if your team has any improvements, they can send a pull request. We'll be happy to review and incorporate that into Crawljax.

Thanks!

**Comment by psiinon** [comment]
Thats great to hear!

I'll make sure our PRs are submitted asap.
