### ISSUE TITLE
How to make crawljax stop listening port 8080?

### ISSUE THREAD

**Issue by 3XclusiVe** [crawljax/crawljax#510]
Ive downloaded crawljax-web-3.6-distribution.zip and started it from command line. Now how can i stop it? I  tried to kill it by PID, but it still can be opened by 0.0.0.0:8080.

**Comment by amesbah** [comment]
If you killed the process running Crawljax, that should be it. What can be opened at 0.0.0.0:8080? Not sure if I understand the question.

**Comment by 3XclusiVe** [comment]
Thank you very much for the reply. It seems the problem was in my browser. It was solved after I cleaned the cache.
