### ISSUE TITLE
Crawljax not crawling through entire website

### ISSUE THREAD

**Issue by sachn1** [crawljax/crawljax#511]
Initially for checking I had taken the AdvancedExample.java and made corresponding changes to see whether it'll crawl through the entire website as it says. 
For that I later tested www.amazon.in in two cases. One with a set of two browsers (unlimited depth and maximum states) and the other with a set of 5 browsers (unlimited depth and maximum states). The reason for such a selection of depth and states is that what we require is to crawl the entire website and we mainly deal with e-commerce websites.

#42 was something similar but with a depth of 1 and setting number of states to be crawled to maximum clicking all links were possible. Unfortunately that was limited to that particular webpage alone. As the depth increased the problem is found to persist.

Please find the below attached output files and please help/recommend the best configurations that would do good!

[amazon 2 browsers.zip](https://github.com/crawljax/crawljax/files/1332919/amazon.2.browsers.zip)
[amazon 5 browsers.zip](https://github.com/crawljax/crawljax/files/1332926/amazon.5.browsers.zip)

Plz respond: @alexnederlof @amesbah /team

Thanks
Sachin Nandakumar

**Comment by amesbah** [comment]
Perhaps give the new version a try. I'm closing this as there is no way for us to reproduce it.
