### ISSUE TITLE
Crawljax Website is a invalid URL

### ISSUE THREAD

**Issue by Troublor** [crawljax/crawljax#520]
`http://crawljax.com/ ` This domain seems to be invalid and it's not the crawljax website.

**Comment by Jeeppler** [comment]
I did experience the same issue.

**Comment by Troublor** [comment]
@Jeeppler It seems that Crawljax people have stopped maintaining the website, see this commit 7822f39.

**Comment by Jeeppler** [comment]
@Troublor thanks for putting the work into searching the commit.

**Comment by amesbah** [comment]
Fixed.
