### ISSUE TITLE
Input specification does not have .field ,how can i specify inputs in the input field of forms in version 4.1?

### ISSUE THREAD

**Issue by maria456123** [crawljax/crawljax#525]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maria456123** [comment]
private static InputSpecification getInputSpecification() {
		InputSpecification input = new InputSpecification();
		input.inputField(InputType.TEXT, new Identification(How.name, "user")).inputValues("admin");
		input.inputField(InputType.TEXT, new Identification(How.name, "pass")).inputValues("secret");
		  return input;
	}
this is how we can do it in version 4.1.

**Comment by yrahulkr** [comment]
Identification is how you identify the target web element. It could be things like "xpath" or "id". Here is the [identification class](https://github.com/crawljax/crawljax/blob/master/core/src/main/java/com/crawljax/core/state/Identification.java) in crawljax. 

Here is an example usage. 


		FormInput username = loginForm.inputField(InputType.TEXT, new Identification(How.name, "user"));
		username.inputValues("admin");
