### ISSUE TITLE
java.lang.NullPointerException 	at com.crawljax.core.state.InMemoryStateFlowGraph.getShortestPath(InMemoryStateFlowGraph.java:267) in version 4.1. 

### ISSUE THREAD

**Issue by maria456123** [crawljax/crawljax#526]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yrahulkr** [comment]
Is it an uncaught exception? Does Crawljax continue after error or does it stop?

**Comment by maria456123** [comment]
The browser window popped up and then the crawljax stopped with this
exception.

**Comment by amesbah** [comment]
Cannot reproduce. Closing for now.
