### ISSUE TITLE
Default remote grid configuration does not work.

### ISSUE THREAD

**Issue by DerekJLeggett** [crawljax/crawljax#528]
**Describe the bug**
Currently when a user wants to run browsers on Selenium grid, the browser(chrome, firefox, etc...) is not specified only "REMOTE". You can only pass in the number of browsers and the grid url. Default capabilities are specified with only platform:ANY. This configuration does not work. User needs to be able to pass in Desired Capabilities as a parameter in order to run crawl tests on Selenium Grid. It is the same way with running the browser locally, in the WebDriverBrowserBuilder class, newChromeBrowser method, you instantiate a generic: ChromeOptions optionsChrome = new ChromeOptions(); You only cover headless and proxy settings. The ChromeOptions/DesiredCapabilities should be passed in from the client as build parameters for local as well as remote browser test execution.
This is a relatively simple fix that would make this tool much more useful!

**To Reproduce**
1. Try and run crawl tests on grid.
2. The lack of configuration options prevent grid from accepting session request.

**Expected behavior**
New session should start on grid.
I have implemented a working code fix locally. I tried committing a branch, I do not have permissions to do so. I'm working off of the 4.1 release tag.

**Comment by amesbah** [comment]
Hi @DerekJLeggett it would be great if you can send a pull request (off of master).

**Comment by DerekJLeggett** [comment]
Hi @amesbah I have my changes committed locally. I am unable to push a new branch though:
derek@PHXL-9P7PMN3:~/git/crawljax$ git push --set-upstream origin UpdateRemoteConfiguration
remote: Permission to crawljax/crawljax.git denied to DerekJLeggett.
fatal: unable to access 'https://github.com/crawljax/crawljax.git/': The requested URL returned error: 403

**Comment by amesbah** [comment]
You can't push directly. You could [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) crawljax and then submit a [PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) from your own fork or local branch.

**Comment by DerekJLeggett** [comment]
@amesbah Thanks for your help. I created PR: https://github.com/crawljax/crawljax/pull/586

**Comment by amesbah** [comment]
Thanks for PR #528, which is now merged.
