### ISSUE TITLE
ArithmeticException: / by zero pixelDensity

### ISSUE THREAD

**Issue by amesbah** [crawljax/crawljax#537]
**Describe the bug**

java.lang.ArithmeticException: / by zero at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getScreenShotAsBufferedImage(WebDriverBackedEmbeddedBrowser.java:924)

Caused by:
```
      BufferedImage resizedImage = new BufferedImage(img.getWidth() / pixelDensity,
          img.getHeight() / pixelDensity, BufferedImage.TYPE_INT_RGB);

```

**Comment by yrahulkr** [comment]
Fixed with commit c43ac1be6dc18e46c3a8ada6332952b0ff00ab4a
