### ISSUE TITLE
Detect clickable elements programmatically 

### ISSUE THREAD

**Issue by amesbah** [crawljax/crawljax#540]
### How it works

Clickable detector is implemented as a plugin that is called whenever a new state is discovered by Crawljax. 
It detects clickables by using `getEventListeners` function in chrome devtools. 

### Requirements: 

- Google Chrome Browser

> BrowserConfiguration.BrowserType = CHROME/CHROME_HEADLESS

- Chrome Developer Tools enabled

> Default BrowserProvider : `BrowserOptions.setUSE_CDP(true)` 
>  Custom BrowserProvider : `WebDriverBackedEmbeddedBrowser.setUSE_CDP(true)`
 
  For example usage, see [ClickableDetectorExample](https://github.com/crawljax/crawljax/tree/master/examples/src/main/java/com/crawljax/examples) in examples module

### Limitations

- Does not work for browsers other than Google Chrome
- If the element interactions are not associated with a corresponding `eventhandler` as determined by browser, then they wont be considered clickables
- Only `click` action is currently supported. Other interactions such as hover are not supported.

**Comment by yrahulkr** [comment]
Feature is available now from 26ba317648aa240c60194c8290d36af7b30b98e5
